# Generated by Django 5.2 on 2025-05-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
