# Generated by Django 5.2 on 2025-05-13 02:25

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='metadata',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='data_3d',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='has_3d_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_processed_path),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='processing_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='analysis_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=api.models.get_upload_path),
        ),
    ]
